# Generated by Django 4.1 on 2023-12-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='census',
            name='born_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='census',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='census',
            name='gender',
            field=models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('NP', 'No response')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id', 'born_date', 'gender', 'city')},
        ),
    ]
