# Generated by Django 4.1 on 2023-12-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_alter_census_unique_together_census_born_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id')},
        ),
    ]
