# Generated by Django 4.1 on 2023-12-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_alter_census_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='city',
            field=models.CharField(choices=[('SE', 'Sevilla'), ('MA', 'Madrid'), ('VAL', 'Valencia'), ('BAR', 'Barcelona'), ('ZAR', 'Zaragoza')], max_length=20, null=True),
        ),
    ]
