# Generated by Django 4.1 on 2023-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='number_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voting',
            name='postproc_type',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('DHONDT', 'DHONDT')], default='IDENTITY', max_length=255),
        ),
    ]
