# Generated by Django 4.1 on 2023-11-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Multiple')], default='S', max_length=1),
        ),
    ]
