# Generated by Django 4.1 on 2023-12-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('C', 'Pregunta clásica'), ('M', 'Pregunta multirrespuesta')], default='C', max_length=1),
        ),
    ]
