# Generated by Django 4.1 on 2023-12-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_voting_campo_personalizable'),
        ('voting', '0005_voting_number_seats_voting_postproc_type'),
    ]

    operations = [
    ]
