# Generated by Django 4.1 on 2023-12-05 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2023, 12, 5)),
        ),
    ]
