# Generated by Django 4.1 on 2023-11-24 14:19

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='a',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='b',
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', base.models.BigBigField()),
                ('b', base.models.BigBigField()),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.vote')),
            ],
        ),
    ]
